FROM python:3.12.4-alpine
EXPOSE 5000
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
ENV DJANGO_SETTINGS_MODULE="itsanapi.settings.docker"
CMD python manage.py migrate && python manage.py loaddata api/fixtures/user_docker.json && python manage.py runserver 0.0.0.0:5000