AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a private Amazon ECR repository

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: true
      RepositoryName: !Sub "${AWS::StackName}"
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"

Outputs:
  RepositoryUri:
    Description: URI of the created ECR repository
    Value: !Sub '${MyECRRepository.RepositoryUri}'
    Export:
      Name: !Sub "${AWS::StackName}-export"