AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Amazon RDS PostgreSQL instance

Parameters:
  DbUserName:
    Type: String
    Description: 'Database username'
  DbPassword:
    Type: String
    Description: 'Database password'

Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for the RDS instance"
      SubnetIds:
        - !ImportValue public-subnet-1-export
        - !ImportValue public-subnet-2-export
      DBSubnetGroupName: "my-db-subnet-group"

  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for RDS instance"
      VpcId: !ImportValue vpc-id-export
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0 # Replace with a more restrictive CIDR range as needed

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: my-postgres-db
      Engine: postgres
      MasterUsername: !Sub "${DbUserName}"
      MasterUserPassword: !Sub "${DbPassword}"
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp2

Outputs:
  DBInstanceEndpoint:
    Description: "The endpoint of the RDS instance"
    Value: !GetAtt MyDBInstance.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-endpoint-export"

  DBInstancePort:
    Description: "The port of the RDS instance"
    Value: !GetAtt MyDBInstance.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-port-export"
