# Generated by Django 5.0.7 on 2024-07-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GameType',
        ),
    ]
