# Generated by Django 5.0.7 on 2024-07-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_game_gametype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
