"""update constraints

Revision ID: 05b3a84eb34e
Revises: 1bca9b27633a
Create Date: 2024-07-11 08:39:55.838294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b3a84eb34e'
down_revision = '1bca9b27633a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('stack',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('github_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('docs_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('docs_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('github_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('stack',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
