"""add contact requests model

Revision ID: 111048745395
Revises: 90c570152df5
Create Date: 2024-07-06 22:58:00.026193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111048745395'
down_revision = '90c570152df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
