"""add projects table

Revision ID: 1bca9b27633a
Revises: b3b58390b557
Create Date: 2024-07-11 07:50:26.825811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bca9b27633a'
down_revision = 'b3b58390b557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('stack', sa.String(length=120), nullable=True),
    sa.Column('github_link', sa.String(length=120), nullable=True),
    sa.Column('docs_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('docs_link'),
    sa.UniqueConstraint('github_link'),
    sa.UniqueConstraint('language'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stack')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
