"""add expired tokens model

Revision ID: 90c570152df5
Revises: 9da64298f75a
Create Date: 2024-07-06 22:44:12.253844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c570152df5'
down_revision = '9da64298f75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_tokens_model',
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expired_tokens_model')
    # ### end Alembic commands ###
