"""initial migration

Revision ID: 9da64298f75a
Revises: 
Create Date: 2024-07-06 22:27:51.857643

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9da64298f75a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "hangman_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("solution", sa.String(length=120), nullable=False),
        sa.Column("attempts_left", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=120), nullable=False),
        sa.Column("masked_word", sa.String(length=120), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hangman_games")
    op.drop_table("users")
    # ### end Alembic commands ###
